# SPDX-License-Identifier: LicenseRef-SinnZeit-1.0
# Copyright © 2025 beNetX – Moritz Oliver Benatzky et al.

# Copyright © 2025 beNetX – Moritz Oliver Benatzky et al.


name: schema-lint

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install check-jsonschema
        run: pip install check-jsonschema
      - name: Validate Dot-Schemas
        run: |
          find dot_schema -type f -name '*.json' -print0 | \
            xargs -0 -n1 -I{} check-jsonschema --schemafile {} {} 
